# Generated by Django 3.1.4 on 2021-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='name',
            field=models.CharField(default='niki', max_length=30),
            preserve_default=False,
        ),
    ]
