# Generated by Django 3.1.4 on 2021-01-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20210101_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
